# Generated by Django 5.0.2 on 2024-02-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autordb',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.RenameField(
            model_name='frasedb',
            old_name='autor',
            new_name='autor_fk',
        ),
        migrations.RemoveField(
            model_name='frasedb',
            name='fecha',
        ),
        migrations.AlterModelTable(
            name='autordb',
            table='Autores',
        ),
    ]
