# Generated by Django 5.0.2 on 2024-02-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_frasedb_options_alter_frasedb_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesionDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Profesión',
                'verbose_name_plural': 'Profesiones',
                'db_table': 'Profesiones',
            },
        ),
        migrations.RemoveField(
            model_name='autordb',
            name='profesion',
        ),
        migrations.AddField(
            model_name='autordb',
            name='profesion',
            field=models.ManyToManyField(to='App1.profesiondb', verbose_name='Profesión'),
        ),
    ]
